#define VERSION L"1.4"

#define MAX_CIVS 50
#define MAX_CIVS_HD 31
#define MAX_CIVS_AOK 18
#define MAX_DRAWNLOG_LINECOUNT 256
#define DLC_AMOUNT 11
#define EDITION_AMOUNT 3
#define MAX_LOADSTRING 100
#define HOTKEY_AMOUNT 38
#define TOOLTIP_AMOUNT 25
#define SOUND_AMOUNT 5
#define LEGACY_JINGLE_AMOUNT 18

#define HOTKEY_ID_TAB 1
#define HOTKEY_ID_SPACE 2
#define HOTKEY_ID_RETURN 3
#define HOTKEY_ID_ESC 4
#define HOTKEY_ID_Z 5
#define HOTKEY_ID_X 6
#define HOTKEY_ID_C 7
#define HOTKEY_ID_V 8
#define HOTKEY_ID_T 9
#define HOTKEY_ID_1 10
#define HOTKEY_ID_2 11
#define HOTKEY_ID_3 12
#define HOTKEY_ID_Q 13
#define HOTKEY_ID_W 14
#define HOTKEY_ID_E 15
#define HOTKEY_ID_A 16
#define HOTKEY_ID_S 17
#define HOTKEY_ID_D 18
#define HOTKEY_ID_F 19
#define HOTKEY_ID_G 20
#define HOTKEY_ID_H 21
#define HOTKEY_ID_R 22
#define HOTKEY_ID_F1 23
#define HOTKEY_ID_B 24
#define HOTKEY_ID_F2 25
#define HOTKEY_ID_F3 26
#define HOTKEY_ID_F4 27
#define HOTKEY_ID_F5 28
#define HOTKEY_ID_F6 29
#define HOTKEY_ID_F9 30
#define HOTKEY_ID_CTRLS 31
#define HOTKEY_ID_CTRLR 32
#define HOTKEY_ID_CTRLF 33
#define HOTKEY_ID_CTRLZ 34
#define HOTKEY_ID_CTRLX 35
#define HOTKEY_ID_CTRLT 36
#define HOTKEY_ID_J 37


#define DT_UNDERLINE 0x80000000
#define MAX_LENGTH 15 

#define MIN_WIDTH 550
#define MIN_HEIGHT 480

#define BUTTON_WIDTH 100
#define BUTTON_HEIGHT 30

#define TOOLTIP_DRAW                0
#define TOOLTIP_RESET               1
#define TOOLTIP_CLEAR               2
#define TOOLTIP_ENABLEALL           3
#define TOOLTIP_DISABLEALL          4
#define TOOLTIP_TECHTREE            5
#define TOOLTIP_REMAININGTOGGLE     6
#define TOOLTIP_DE                  7
#define TOOLTIP_HD                  8
#define TOOLTIP_AOK                 9
#define TOOLTIP_ROYALS			    10
#define TOOLTIP_ROME				11
#define TOOLTIP_INDIA				12
#define TOOLTIP_DUKES				13
#define TOOLTIP_WEST				14
#define TOOLTIP_KHANS				15
#define TOOLTIP_RAJAS				16
#define TOOLTIP_AFRICANS			17
#define TOOLTIP_FORGOTTEN			18
#define TOOLTIP_AOC				    19
#define TOOLTIP_AUTOTOGGLE  	    20
#define TOOLTIP_AUTORESET  	        21
#define TOOLTIP_OPTIONS             22
#define TOOLTIP_SURVAPP			    23
#define TOOLTIP_KINGDOMS            24
